language: node_js
node_js: node
cache:
  directories:
    - node_modules
#before_install:
#- npm config set registry https://registry.npm.taobao.org
#- npm config get registry
install: npm install
script:
- webpack --env build
- webpack --progress --colors --env dev
after_script:
- git config --global user.name 'FDD'
- git config --global user.email 'smileFDD@gmail.com'
#- sed -i'' "s~git@github.com/sakitam-fdd/HMap.git~https://${github}:x-oauth-basic@github.com/sakitam-fdd/HMap.git~"
after_success:
- git commit
- git push